plugins:
  zspace_upload_wizard_url:
    client: true
    default: ''
  zspace_display_upload_below_topic_title:
    client: true
    default: false
  zspace_community_uploads_category_id:
    type: category
    default: -1